import React from "react";
import Layout from "../components/Layout";
import { NavLink } from "react-router-dom";

const RefundPolicyPage = () => {
  return (
    <Layout>
      <div className="lg:mx-28 px-5 lg:px-10 py-10 font-base bg-white">
        <div className="flex justify justify-between border-b-2 pb-5 mb-5 font-medium ">
          <NavLink
            to="/privacy-policy"
            className={({ isActive }) =>
              isActive ? "text-primary font-semibold" : " hover:text-primary"
            }
          >
            Privacy Policy
          </NavLink>
          <NavLink
            to="/terms-and-condition"
            className={({ isActive }) =>
              isActive ? "text-primary font-semibold" : "hover:text-primary"
            }
          >
            Terms & Conditions
          </NavLink>
          <NavLink
            to="/refund-policy"
            className={({ isActive }) =>
              isActive ? "text-primary font-semibold" : "hover:text-primary"
            }
          >
            Return and Refund Policy
          </NavLink>
        </div>
        <h1 className="text-2xl font-bold text-gray-700 mb-5">
          Return & Refund Policy
        </h1>
        <p className="font-semibold text-sm mb-5">Updated at 2023-07-23</p>

        <h1 className="text-xl font-bold text-gray-700 my-5">
          Definitions and key terms
        </h1>
        <p>
          To help explain things as clearly as possible in this Return and Refund
          Policy, every time any of these terms are referenced, they are strictly
          defined as:
        </p>
        <ul className="list-disc mx-3 my-5 space-y-6">
          <li>
            Cookie: small amount of data generated by a website and saved by
            your web browser. It is used to identify your browser, provide
            analytics, remember information about you such as your language
            preference or login information.
          </li>
          <li>
            Company: when this policy mentions “Company,” “we,” “us,” or “our,”
            it refers to MAANG Careers, that is responsible for your information
            under this Return & Refund Policy.
          </li>
          <li>
            Customer: refers to the company, organization or person that signs
            up to use the MAANG Careers Service to manage the relationships with
            your consumers or service users.
          </li>
          <li>
            Device: any internet connected device such as a phone, tablet,
            computer or any other device that can be used to visit MAANG Careers
            and use the services.
          </li>
          <li>
            Service: refers to the service provided by MAANG Careers as described
            in the relative terms (if available) and on this platform.
          </li>
          <li>
            Website: site, which can be accessed via this URL :{" "}
            <a
              className="font-bold text-primary"
              href="https://www.maangcareers.com"
            >
              https://www.maangcareers.com
            </a>
          </li>
          <li>
            You: a person or entity that is registered with MAANG Careers to use
            the Services.
          </li>
        </ul>

        <h1 className="text-xl font-bold text-gray-700 my-5">
          Return & Refund Policy
        </h1>
        <p className="mb-3">
          Thanks for your course purchase at MAANG Careers. There are terms and conditions that apply to transactions at MAANG Careers. We'll be as brief as our attorneys will allow. The main thing to remember is that by making a purchase at MAANG Careers, you agree to the terms set forth below, along with the policy.
        </p>

        <p>
          If there's something wrong with the course you bought, or if you are not
          happy with it, you will not be able to issue a refund.
        </p>

        <h1 className="text-xl font-bold text-gray-700 my-5">Refunds</h1>
        <p className="mb-3">
          We pride ourselves on serving our customers with the best IT training courses. Every single course that you choose is thoroughly revised, and evaluated with utmost care. We do this to ensure that you fall in love with our courses.
        </p>
        <p className="mb-3">
          Please note that, any purchases made on this MAANG Careers website, the refund is strictly not applicable for the courses offered.
        </p>
        <p className="mb-3">
          We follow certain policies to ensure transparency, efficiency and
          quality customer care:
        </p>
        <ul className="list-disc space-y-4 mx-3 my-5">
          <li>
            Refunds are NOT given for any purchases made online.
          </li>
          <li>We DO NOT encourage exchanges of our courses.</li>
        </ul>
        <p className="text-xl font-bold text-gray-700 my-5">
          For International Orders:
        </p>
        <ul className="list-disc space-y-4 mx-3 my-5">
          <li>We DO NOT support Exchanges or Returns.</li>
          <li>
            If you face any issues, please contact our Support Team immediately.
          </li>
        </ul>

        <h1 className="text-xl font-bold text-gray-700 my-5">Your Consent</h1>
        <p>
          By using our website, registering an account, or making a purchase,
          you hereby consent to our Return & Refund Policy and agree to its
          terms.
        </p>

        <h1 className="text-xl font-bold text-gray-700 my-5">
          Changes To Our Return & Refund Policy
        </h1>
        <p>
          Should we update, amend or make any changes to this document so that
          they accurately reflect our Service and policies. Unless otherwise
          required by law, those changes will be prominently posted here. Then,
          if you continue to use the Service, you will be bound by the updated
          Return & Refund Policy. If you do not want to agree to this or any
          updated Return & Refund Policy, you can delete your account.
        </p>
      </div>
    </Layout>
  );
};

export default RefundPolicyPage;
